### ISSUE TITLE
More references on object safety?

### ISSUE THREAD

**Issue by hengchu** [dtolnay/dyn-clone#2]
I have been trying to wrap my head around why object safety rules out `Sized` traits, and the Rust book does not seem to explain this in details. Is there some design document/paper that I can read on to understand the technical details of object safety restriction? I would also like to understand the techniques used for implementing `dyn-clone` in case they are explained somewhere.

Thanks!

**Comment by phlopsi** [comment]
The first question would be better suited for https://users.rust-lang.org

Anyway, it's quick to answer. Trait objects are dynamically sized and `dyn MyTrait: MyTrait` must hold true, but if the trait rules out dynamically-sized types by declaring `Self: Sized`, then `dyn MyTrait` cannot satisfy `MyTrait`. In conclusion, you cannot create the trait object `dyn MyTrait`.

The technique used here is fairly straightforward. Returning `Self` from a trait method is object-unsafe, but that's exactly what `Clone::clone` does. To get around this limitation, you have to return a type-erased type, in this case `*mut ()`. The problem is, that `*mut ()` has the same size as a pointer, but not every type is equally sized. The trick is to box the value, which has a data pointer and potentially a length (for slices) or a vtable pointer (for trait objects). Only the data pointer has to be returned, because the vtable pointer or length stay the same when cloning. This pointer can then be turned back to the actual type via `dyn_clone::clone(_box)`.
