### ISSUE TITLE
Is it possible to clone trait object into Box<dyn Trait> and not just Box<Trait>?

### ISSUE THREAD

**Issue by jockbert** [dtolnay/dyn-clone#26]
I apologize in advance in case this issue is more of a Rust-inexperience-thing than a limitation or quirk with *dyn-clone*. 

Is there a way to in a trait object method, clone `self` into a `Box<dyn Trait>` instead of just a `Box<Trait>`?

```rust
use dyn_clone::DynClone;

dyn_clone::clone_trait_object!(Foo);

pub trait Foo: DynClone {
    fn bar_something(&self) {
        let boxed_self: Box<dyn Foo> = dyn_clone::clone_box(self);
        baz_accepting_trait_object(boxed_self)
    }
}

fn baz_accepting_trait_object(my_foo: Box<dyn Foo>) {
    // do something generic applicable to all implementers of Foo...
}

#[derive(Clone)]
struct UserOfFoo {}
impl Foo for UserOfFoo {}

fn other_place_of_use() {
    let foo: Box<dyn Foo> = Box::new(UserOfFoo {});
    foo.bar_something();
}
```

The code above yields the following error message:

```
error[E0277]: the size for values of type `Self` cannot be known at compilation time
 --> src/lib.rs:5:61
  |
7 |         let boxed_self: Box<dyn Foo> = dyn_clone::clone_box(self);
  |                                                             ^^^^ doesn't have a size known at compile-time
  |
  = note: required for the cast from `&Self` to `&dyn Foo`
help: consider further restricting `Self`
  |
6 |     fn bar_something(&self) where Self: Sized {
  |                             +++++++++++++++++
```
I try to resolve this as recommended in error message, restricting `Self` to be `Sized`:

```diff
 pub trait Foo: DynClone {
     fn bar_something(&self)
+    where
+        Self: Sized,
     {
         let boxed_self: Box<dyn Foo> = dyn_clone::clone_box(self);
         baz_accepting_trait_object(boxed_self)
     }
 }
```

It solves the previous error, but makes `bar_something` unusable from other places, which to my understanding do make sense:

```
error: the `bar_something` method cannot be invoked on a trait object
  --> src/lib.rs:23:9
   |
8  |         Self: Sized,
   |               ----- this has a `Sized` requirement
...
25 |     foo.bar_something();
   |         ^^^^^^^^^^^^^
```

I just don't understand how to apply *dyn-clone* correctly here. What have I missed?

# For reference - alternative working solution not using *dyn-clone*  

I'm trying to migrate to *dyn-clone* from a home baked solution using the pattern described in rust-lang froum topic [is-it-possible-to-clone-a-boxed-trait-object](https://users.rust-lang.org/t/solved-is-it-possible-to-clone-a-boxed-trait-object/1714/7). That solution works fine for my purposes:

```rust
pub trait DynCloneFoo {
    fn clone_box(&self) -> Box<dyn Foo>;
}

impl<T> DynCloneFoo for T
where
    T: Foo + Clone + 'static,
{
    fn clone_box(&self) -> Box<dyn Foo> {
        Box::new(self.clone())
    }
}

impl Clone for Box<dyn Foo> {
    fn clone(&self) -> Self {
        self.clone_box()
    }
}

pub trait Foo: DynCloneFoo {
    fn bar_something(&self) {
        let boxed_self: Box<dyn Foo> = self.clone_box();
        baz_accepting_trait_object(boxed_self)
    }
}

fn baz_accepting_trait_object(_my_foo: Box<dyn Foo>) {
    // do something generic applicable to all implementers of Foo...
}

#[derive(Clone)]
struct UserOfFoo {}
impl Foo for UserOfFoo {}

fn other_place_of_use() {
    let foo: Box<dyn Foo> = Box::new(UserOfFoo {});
    foo.bar_something();
}
```

**Comment by doutv** [comment]
dyn_clone::clone_trait_object!

**Comment by dtolnay** [comment]
Fundamentally, the conversion from concrete type `Self` to trait object `dyn Foo` needs to happen in an `impl` block, not in a `trait`. In your code at the top of the issue, you have that conversion inside `trait` which is not going to work. The line is `let boxed_self: Box<dyn Foo> = dyn_clone::clone_box(self)`. It starts out with `self` having the type `&Self`, and either **before** or **after** the call to `clone_box` you are expecting a coercion to happen. Either it coerces from `&Self` to `&dyn Foo` in order to call `clone_box::<dyn Foo>`, or it calls `clone_box::<Self>` which returns `Box<Self>` followed by a coercion from `Box<Self>` to `Box<dyn Foo>`. Either way there is a conversion in there from `Self` to `dyn Foo` and that is not something you can do in a trait.

The code at the bottom of the issue has a conversion from `Self` to `dyn Foo` in an `impl` which is why it works. `Box::new(self.clone())` where `self` has type `&Self`, `self.clone()` is `Self`, and `Box::new(self.clone())` is `Box<Self>`. So there's the coercion from `Box<Self>` to `Box<dyn Foo>`.

With dyn-clone, something like:

```rust
pub trait AsDynFoo {
    fn as_dyn_foo(&self) -> &dyn Foo;
}

impl<T: Foo> AsDynFoo for T {
    fn as_dyn_foo(&self) -> &dyn Foo {
        self
    }
}

pub trait Foo: AsDynFoo + DynClone {
    fn bar_something(&self) {
        let boxed_self = dyn_clone::clone_box(self.as_dyn_foo());
        baz_accepting_trait_object(boxed_self)
    }
}

fn baz_accepting_trait_object(my_foo: Box<dyn Foo + '_>) {...}
```
